[workspace]
resolver = "3"
members = [
	".",
	"inline-config-derive",
]

[package]
name = "inline-config"
version = "0.0.1"
edition = "2024"

[features]
default = ["json", "toml", "yaml"]
indexmap = ["inline-config-derive/indexmap", "dep:indexmap"]
json = ["inline-config-derive/json"]
toml = ["inline-config-derive/toml"]
yaml = ["inline-config-derive/yaml"]

[dependencies.inline-config-derive]
path = "inline-config-derive"

[dependencies.indexmap]
version = "2.12.1"
optional = true
